[package]
name = "rsfxr"
version = "0.1.0"
edition = "2021"
description = "A small Rust library for generating random sound effects."
license = "Apache-2.0"

[dependencies]
alsa = "0.9.1"
rand = "0.8.5"
